[package]
name = "logm"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive", "env"] }
colored = "3.0.0"
serde = { version = "1.0.228", features = ["derive"] }
once_cell = "1.21.3"
confy = "1.0.0"
chrono = "0.4.42"
atty = "0.2.14"
